In [7]:
import numpy as np

M = np.array([
    [100 ,50, 0],
    [150, 100, 50],
    [200, 150, 100]
    ])

E = np.array([
    [20, 10, 5],
    [30, 20, 10],
    [40, 30, 15]
    ])
scalar = 0.5

def change_contrast(M, scalar):
    return M * scalar

def change_brightness(M, scalar):
    return M + scalar

def blending(M, E, alpha):
    if not (0 <= alpha <= 1):
        raise ValueError("Alpha must be between 0 and 1")

    return alpha * M + (1 - alpha) * E


In [8]:
print("We are going to change contrast of the image")
user_input = input("Default scalar: 0.5, click enter to continue, or type new scalar, 0 < scalar < 1 will make image darker, scalar > 1 will make image brighter: ")
if user_input.strip() == "":
    scalar = 0.5
    print("Using default scalar: 0.5")
else:
    try:
        scalar = float(user_input)
    except ValueError:
        print("Invalid input. Using default scalar: 0.5")
        scalar = 0.5
print(f"After apply {scalar} to image matrix will be:")
print(change_contrast(M, scalar))

We are going to change contrast of the image
Using default scalar: 0.5
After apply 0.5 to image matrix will be:
[[ 50.  25.   0.]
 [ 75.  50.  25.]
 [100.  75.  50.]]


In [9]:
print("We are going to change brightness of the image")
user_input = input("Default scalar: 25, click enter to continue, or type new scalar, scalar > 0 will make image brighter, scalar < 0 will make image darker: ")
if user_input.strip() == "":
    scalar = 25
    print("Using default scalar: 25")
else:
    try:
        scalar = float(user_input)
    except ValueError:
        print("Invalid input. Using default scalar: 25")
        scalar = 25
print(f"After apply {scalar} to image matrix will be:")
result = change_brightness(M, scalar)
print(result)
if np.max(result) > 255 or np.min(result) < 0:
    print("but value of pixel can't be more than 255 or less than 0, so we need to clip values:")
    print(np.clip(result, 0, 255))

We are going to change brightness of the image
Using default scalar: 25
After apply 25 to image matrix will be:
[[125  75  25]
 [175 125  75]
 [225 175 125]]


In [10]:
print("We are going to blend two images")
user_input = input("Default alpha: 0.8, click enter to continue, or type new alpha, standard alpha should be 0 < alpha < 1, if alpha close to 0, first image will be more visible, if alpha close to 1, second image will be more visible: ")
if user_input.strip() == "":
    alpha = 0.8
    print("Using default alpha: 0.8")
else:
    try:
        alpha = float(user_input)
        if not (0 <= alpha <= 1):
            print("Alpha must be between 0 and 1. Using default alpha: 0.8")
            alpha = 0.8
    except ValueError:
        print("Invalid input. Using default alpha: 0.8")
        alpha = 0.8
print(f"After apply {alpha} to image matrix will be:")
result = blending(M, E, alpha)
print(result)
if np.max(result) > 255 or np.min(result) < 0:
    print("but value of pixel can't be more than 255 or less than 0, so we need to clip values:")
    print(np.clip(result, 0, 255))

We are going to blend two images
Using default alpha: 0.8
After apply 0.8 to image matrix will be:
[[ 84.  42.   1.]
 [126.  84.  42.]
 [168. 126.  83.]]
